version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: yellow-pages-postgres-container
    environment:
      POSTGRES_DB: yellow-pages
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./data:/data

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yellow-pages-nodejs-container
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    depends_on:
      - postgres
